### ISSUE TITLE
Ads Manager: Campaign Creator V2.1 

### ISSUE THREAD

**Issue by dlipeles** [brave/ads-ui#237]
#### P1
- [x] On submit of campaign show loading indicator, also catch errors gracefully, link to campaigns page.
- [x] Add validation: Target URL in creative should be valid url prefixed by https:// (match server) 
- [x] Implement Edit buttons on review page #236 
- [x] Ensure bid is nulled when currency is changed from campaign page (& investigate #233) 
- [x] Implement delete mechanism for ad sets 
- [x] Implement delete mechanism for ads
- [x] Comment out cpl, cpx for now (from user side) - #235 
- [x] Comment out platforms and conversion for now (from user side) - #235 
- [x] Update user bid to follow rate CPM / CPC rate card. 

#### P2

- [x] Add validation: Bid cannot be greater than daily budget 
- [x] Improve creative preview (Accuracy / prevent text overflow / reduce lag) 
- [x] Add "Coming Soon" to Quick order and Automated Order #232  
- [x] Fix subheading in Ad Set #234 

#### Ad Ops

- [x] Notify in #ads-bot when new campaign is created through self-service
