### ISSUE TITLE
Prepare Ads Manager for BuySellAds & Brave Sales Team

### ISSUE THREAD

**Issue by dlipeles** [brave/ads-ui#294]
- [ ] Webhooks on Creative Instance (confirm if needed)
- [ ] Pricing on CPC / CPI / CP(X) campaigns 
- [ ] List of current campaigns with relevant stats (budget, spend, start date, etc.) #246 
- [ ] Ensure platform / conversion audience is available. #262 
- [ ] Fix bug on campaign budget #261 
- [ ] Conversion terminology #250 
- [ ] Price terminology #249 
- [ ] Stripe Pre-Auth credit card check
- [ ] Permissions with JWT token
- [ ] Ad Ops team slack / ads - dev
